In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
## Define the vocabulary size
voc_size=10000

In [14]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [15]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4297, 2598, 1860, 145],
 [4297, 2598, 1860, 6752],
 [4297, 4987, 1860, 4235],
 [7127, 2290, 6755, 2264, 4656],
 [7127, 2290, 6755, 2264, 9838],
 [7026, 4297, 900, 1860, 3509],
 [4074, 4657, 5274, 2264]]

In [16]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4297 2598 1860  145]
 [   0    0    0    0 4297 2598 1860 6752]
 [   0    0    0    0 4297 4987 1860 4235]
 [   0    0    0 7127 2290 6755 2264 4656]
 [   0    0    0 7127 2290 6755 2264 9838]
 [   0    0    0 7026 4297  900 1860 3509]
 [   0    0    0    0 4074 4657 5274 2264]]


In [21]:
## feature representation
dim=10

In [22]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 258ms/step


array([[[ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,
          0.03800774, -0.00290797, -0.02938236, -0.04901977,
          0.04402821,  0.02208464],
        [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,
          0.03800774, -0.00290797, -0.02938236, -0.04901977,
          0.04402821,  0.02208464],
        [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,
          0.03800774, -0.00290797, -0.02938236, -0.04901977,
          0.04402821,  0.02208464],
        [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,
          0.03800774, -0.00290797, -0.02938236, -0.04901977,
          0.04402821,  0.02208464],
        [-0.02522376,  0.01597908,  0.04711701,  0.00498692,
          0.04358616,  0.01893887, -0.01436838,  0.01730558,
         -0.00541645, -0.01634895],
        [ 0.00368102,  0.01514939,  0.0324267 , -0.00286331,
          0.00542508,  0.03170092, -0.01675736, -0.01101768,
          0.04778178, -0.04276706],
        [ 0.00548341,  0.00655147, -0.02202913,  0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 4297, 2598, 1860,  145])

In [26]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 166ms/step


array([[ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,  0.03800774,
        -0.00290797, -0.02938236, -0.04901977,  0.04402821,  0.02208464],
       [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,  0.03800774,
        -0.00290797, -0.02938236, -0.04901977,  0.04402821,  0.02208464],
       [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,  0.03800774,
        -0.00290797, -0.02938236, -0.04901977,  0.04402821,  0.02208464],
       [ 0.01322783, -0.0022002 ,  0.04290907, -0.03053975,  0.03800774,
        -0.00290797, -0.02938236, -0.04901977,  0.04402821,  0.02208464],
       [-0.02522376,  0.01597908,  0.04711701,  0.00498692,  0.04358616,
         0.01893887, -0.01436838,  0.01730558, -0.00541645, -0.01634895],
       [ 0.00368102,  0.01514939,  0.0324267 , -0.00286331,  0.00542508,
         0.03170092, -0.01675736, -0.01101768,  0.04778178, -0.04276706],
       [ 0.00548341,  0.00655147, -0.02202913,  0.03993214,  0.00928264,
        -0.01133008, -0.02888306, -0.02474293